FROM ubuntu:16.04
MAINTAINER Mohanad Ahmed (mohanadahmedibrahim@gmail.com) Suheel Yousuf Wani <suheelhamdani@gmail.com> 

# 1. general updates & installing necessary Linux components

RUN apt-get update -y && apt-get install -y \
    bzip2 \
    gcc \
    git \
    less \
    libncurses-dev \
    make \
    time \
    unzip \
    vim \
    wget \
    zlib1g-dev \
    liblz4-tool \
    python3-pip

# conda and pysam
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh && bash Miniconda3-py38_4.10.3-Linux-x86_64.sh -p /miniconda -b
ENV PATH=/miniconda/bin:$PATH
RUN conda update -y conda \
    && rm Miniconda3-py38_4.10.3-Linux-x86_64.sh
RUN conda config --add channels r \
    && conda config --add channels bioconda \
    && conda install -c conda-forge libgcc-ng \
    && conda install -c bioconda samtools \
    && conda install -c bioconda bwa \
    && conda install -c bioconda fastqc \
    && conda install -c bioconda trimmomatic \
    && conda install -c bioconda spades \
    && conda install -c bioconda quast \
    && conda install -c bioconda ragtag \

RUN apt-get update -y && apt-get install -y
